apiVersion: v1
kind: ConfigMap
metadata:
  name: inv-conf
data:
  application.properties: |
    server.port=8082

    spring.datasource.url = jdbc:postgresql://database-1.c2wrz5f8ybha.us-east-1.rds.amazonaws.com:5432/postgres
    spring.datasource.username = postgres
    spring.datasource.password = mystrongpassword!

    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

    spring.jpa.hibernate.ddl-auto = update
    spring.jpa.show-sql = true
    spring.jpa.generate-ddl=true
    spring.jackson.default-property-inclusion = NON_NULL

    spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=https://demo.plainid.cloud/auth/realms/demo/protocol/openid-connect/token/introspect
    spring.security.oauth2.resourceserver.opaquetoken.client-id=spring
    spring.security.oauth2.resourceserver.opaquetoken.client-secret=xlN2CykPxym4IVeWXSeENs8k6sf321KR
    
    plainid.sqlpdp.pdpUrl=http://sql-authz-sql-pdp-modifier.default:8080/resql
    plainid.sqlpdp.clientID=PZWLHTZ4SP1QAJECAICW
    plainid.sqlpdp.clientSecret=oVaAwsSTFMG91RmPKAQqHxwPMU0nyTpBLXotumtg
    plainid.sqlpdp.emptyCLSTreatAsPermitted=false
    plainid.sqlpdp.ignoreRuntimeCLSResponse=false
    plainid.sqlpdp.ignoreSqlPdpServiceErrors=true
    plainid.sqlpdp.oppositeColumnFilteringBehavior=false
    plainid.sqlpdp.expandStarColumn=false
    plainid.sqlpdp.policiesJoinOperation=OR
    plainid.sqlpdp.runtimeCLSAsMasked=true
    plainid.sqlpdp.enabled=true
    plainid.sqlpdp.jwtPassthrough: true
    plainid.sqlpdp.requestMapping: [ { "source": "url","sourceKey": "/account/(.+)/bills","target": "environment","targetKey": "account" } ]
    logging.level.com.plainid = TRACE
